/* TPC-H Query 2 - Adaptada para SQLite */
SELECT 
    S_ACCTBAL, 
    S_NAME, 
    N_NAME, 
    P_PARTKEY, 
    P_MFGR, 
    S_ADDRESS, 
    S_PHONE, 
    S_COMMENT
FROM 
    PART, 
    SUPPLIER, 
    PARTSUPP, 
    NATION, 
    REGION
WHERE 
    P_PARTKEY = PS_PARTKEY 
    AND S_SUPPKEY = PS_SUPPKEY 
    AND P_SIZE = 7 
    AND P_TYPE LIKE '%ECONOMY ANODIZED STEEL' 
    AND S_NATIONKEY = N_NATIONKEY 
    AND N_REGIONKEY = R_REGIONKEY 
    AND R_NAME = 'EUROPE' 
    AND PS_SUPPLYCOST = (
        SELECT MIN(PS_SUPPLYCOST) 
        FROM PARTSUPP AS ps2
        JOIN SUPPLIER AS s2 ON s2.S_SUPPKEY = ps2.PS_SUPPKEY
        JOIN NATION AS n2 ON s2.S_NATIONKEY = n2.N_NATIONKEY
        JOIN REGION AS r2 ON n2.N_REGIONKEY = r2.R_REGIONKEY
        WHERE ps2.PS_PARTKEY = PART.P_PARTKEY
        AND r2.R_NAME = 'EUROPE'
    )
ORDER BY 
    S_ACCTBAL DESC, 
    N_NAME, 
    S_NAME, 
    P_PARTKEY
LIMIT 100;
