version: '3.1'

networks:
  mynetwork:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/opt --lower-case-table-names=1
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./tpch_load_data_test:/opt
      - ./tpch_load_data_test/load.sh:/docker-entrypoint-initdb.d/load.sh
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - mynetwork

  workload:
    image: workload-executor
    restart: always
    build:
      context: ./tpch_workload_executor
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
      - webapi
    links:
      - mysql
      - webapi
    networks:
      - mynetwork

  webapi:
    build:
      context: ./webapi/demo/demo
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./tpch_workload_executor/output:/usr/local/tomcat/docker-compose/tpch_workload_executor/output"
    networks:
      - mynetwork

  outertuning:
    image: outertuning
    restart: always
    depends_on:
      - mysql
      - webapi
    links:
      - mysql
      - webapi
    ports:
      - 80:8080
    volumes:
      - "./tpch_workload_executor/output:/usr/local/tomcat/docker-compose/tpch_workload_executor/output"
    networks:
      - mynetwork

